// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../../../../app/(admin)/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/bikes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/bikes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inquiries">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/reports/[vendorId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/[vendorId]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/reports/[vendorId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(admin)/dashboard/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendors">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/auth/set-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/set-password">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/auth/set-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/register/vendor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/vendor">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/register/vendor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(legal)/cancellation-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cancellation-policy">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(legal)/cancellation-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(legal)/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(legal)/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(legal)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(legal)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(legal)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(legal)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/bikes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bikes/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/bikes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/bikes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/bikes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/book/[reservationId]/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/[reservationId]/complete">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/book/[reservationId]/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/book/[reservationId]/pay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/[reservationId]/pay">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/book/[reservationId]/pay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/card">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/favorites">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/history">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/messages">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/notifications">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/reservations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/reservations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/settings">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/analytics/bike-performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/analytics/bike-performance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/analytics/bike-performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/analytics/bike-pv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/analytics/bike-pv">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/analytics/bike-pv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/analytics/shop-performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/analytics/shop-performance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/analytics/shop-performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/analytics/shop-pv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/analytics/shop-pv">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/analytics/shop-pv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/announcements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/announcements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/announcements/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/announcements/new">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/announcements/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/announcements">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/bikes/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/bikes/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/bikes/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/bikes/archived/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/bikes/archived">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/bikes/archived/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/bikes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/bikes/new">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/bikes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/bikes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/bikes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/calendar">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/campaigns">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/customers">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/exports/insurance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/exports/insurance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/exports/insurance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/exports/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/exports/logs">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/exports/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/exports/rental-record/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/exports/rental-record">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/exports/rental-record/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/exports/royalty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/exports/royalty">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/exports/royalty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/gear/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/gear/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/gear/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/gear/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/gear/new">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/gear/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/gear/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/gear">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/gear/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/inquiries/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/inquiries/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/inquiries">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/manual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/manual">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/manual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/messages">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/notifications">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/options/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/options/new">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/options/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/options/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/options">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/options/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/pricing">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reports/bikes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reports/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reports/bikes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reports/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reports/customers">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reports/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reports">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reports/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reports/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reports/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reports/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reports/sales">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reports/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reservations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reservations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reservations/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reservations/export">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reservations/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reviews/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reviews/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reviews/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/settings">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/shop/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/shop/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/shop/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/shop/closures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/shop/closures">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/shop/closures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/shop">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inquiries">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payouts">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/admin/vendors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vendors">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/admin/vendors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/auth/ban-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/ban-check">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/auth/ban-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/auth/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/auth/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/bikes/[id]/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bikes/[id]/availability">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/bikes/[id]/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/bikes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bikes/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/bikes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/bikes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/bikes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/cron/booking-reminder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/booking-reminder">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/cron/booking-reminder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/cron/expire-pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/expire-pending">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/cron/expire-pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/cron/monthly-payout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/monthly-payout">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/cron/monthly-payout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/cron/no-show/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/no-show">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/cron/no-show/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/cron/review-reminder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/review-reminder">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/cron/review-reminder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/favorites">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/insurance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insurance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/insurance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/options">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/page-views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/page-views">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/page-views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/reservations/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/reservations/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/reservations/[id]/checkin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]/checkin">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/reservations/[id]/checkin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/reservations/[id]/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]/checkout">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/reservations/[id]/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/square/charge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/square/charge">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/square/charge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/square/refund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/square/refund">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/square/refund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/square/register-card/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/square/register-card">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/square/register-card/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/users/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/delete">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/users/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/analytics/bike-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/analytics/bike-performance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/analytics/bike-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/analytics/bike-pv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/analytics/bike-pv">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/analytics/bike-pv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/analytics/shop-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/analytics/shop-performance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/analytics/shop-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/analytics/shop-pv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/analytics/shop-pv">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/analytics/shop-pv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/announcements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/announcements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/announcements">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/bikes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/bikes/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/bikes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/bikes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/bikes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/business-hours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/business-hours">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/business-hours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/closures/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/closures/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/closures/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/closures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/closures">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/closures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/customers">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/exports/insurance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/exports/insurance">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/exports/insurance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/exports/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/exports/logs">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/exports/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/exports/rental-record/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/exports/rental-record">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/exports/rental-record/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/exports/royalty/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/exports/royalty">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/exports/royalty/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/holidays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/holidays">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/holidays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/inquiries/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/inquiries/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/inquiries">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/options/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/options/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/options/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/options">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/pricing">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reports/bikes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reports/bikes">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reports/bikes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reports/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reports/customers">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reports/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reports/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reports/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reports/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reports/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reports/sales">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reports/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/[id]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations/[id]/confirm">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/[id]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/[id]/contract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations/[id]/contract">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/[id]/contract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/[id]/memo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations/[id]/memo">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/[id]/memo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/[id]/mileage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations/[id]/mileage">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/[id]/mileage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations/export">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/reservations">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/shop-reviews/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/shop-reviews/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/shop-reviews/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/shop-reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/shop-reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/shop-reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendor/shop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/shop">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendor/shop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/api/vendors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors">> = Specific
  const handler = {} as typeof import("../../../../../../../app/api/vendors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../../../../app/(admin)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(admin)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(legal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(legal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(user)/mypage/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/mypage">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(user)/mypage/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/(vendor)/vendor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/vendor">> = Specific
  const handler = {} as typeof import("../../../../../../../app/(vendor)/vendor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
